services:
  - type: web
    name: borrowers-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
  - type: web
    name: borrowers-mcp
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run mcp-http 